public virtual class trigger_Domain 
{
    public virtual void beforeInsert(List<sObject> newRecords)
    {

    }

    public virtual void beforeUpdate(List<sObject> newRecords, List<sObject> oldRecords)
    {
        
    }

    public virtual void beforeDelete(List<sObject> newRecords)
    {
        
    }

    public virtual void afterInsert(List<sObject> newRecords)
    {
        
    }

    public virtual void afterUpdate(List<sObject> newRecords, List<sObject> oldRecords)
    {
        
    }

    public virtual void afterDelete(List<sObject> newRecords)
    {
        
    }

    public virtual void beforeInsert(Map<Id, sObject> newRecords)
    {

    }

    public virtual void beforeUpdate(Map<Id, sObject> newRecords, Map<Id, sObject> oldRecords)
    {
        
    }

    public virtual void beforeDelete(Map<Id, sObject> newRecords)
    {
        
    }

    public virtual void afterInsert(Map<Id, sObject> newRecords)
    {
        
    }

    public virtual void afterUpdate(Map<Id, sObject> newRecords, Map<Id, sObject> oldRecords)
    {
        
    }

    public virtual void afterDelete(Map<Id, sObject> newRecords)
    {
        
    }
}